#!/bin/bash

# Github release to base from
if [ -z $ARCVERSION ]; then
    ARCVERSION="20210127"
fi

# Arc colors
## SCSS
A_BASE="ee00ff"
A_TEXT="ee00ff"
A_BG="ee00ff"
A_FG="$A_TEXT"
A_SELECTED_FG="ee00ff"
A_SELECTED_BG="ee00ff"
A_WARNING="ee00ff"
A_ERROR="ee00ff"
A_SUCCESS="ee00ff"
A_DESTRUCTIVE="ee00ff"
A_SUGGESTED="ee00ff"
A_DROP_TARGET="ee00ff"
A_WM_BUTTON_CLOSE_BG="ee00ff"
A_WM_BUTTON_CLOSE_HOVER_BG="ee00ff"
A_WM_BUTTON_CLOSE_ACTIVE_BG="ee00ff"
A_WM_ICON_CLOSE_BG="ee00ff"
A_WM_BUTTON_HOVER_BG="ee00ff"
A_WM_BUTTON_ACTIVE_BG="$A_SELECTED_BG"
A_WM_BUTTON_HOVER_BORDER="ee00ff"
A_WM_ICON_BG="ee00ff"
A_WM_ICON_UNFOCUSED_BG="ee00ff"
A_WM_ICON_HOVER_BG="ee00ff"
A_WM_ICON_ACTIVE_BG="$A_SELECTED_FG"
A_WINDOW_BG="ee00ff"
A_DARK_SIDEBAR_FG="ee00ff"
## SVG
A_BLUE="ee00ff" # Duplicate of $A_SELECTED_BG
A_WHITE="ee00ff"
A_LIGHT_MENUBAR="ee00ff"
A_DARK="ee00ff" # Duplicate of $A_BG
A_DARKEST="ee00ff" # Duplicate of $A_WM_ICON_CLOSE_BG
A_DARKEST2="ee00ff"
A_DARK_BUTTON="ee00ff"
A_LIGHT_BUTTON="ee00ff"
A_OTHER_LIGHT_BUTTON="ee00ff"
A_MODAL="ee00ff"
A_ASSET_DARK="ee00ff"
A_ASSET_DARK2="ee00ff"
A_ASSET_GREY="ee00ff"
A_ASSET_BORDER="ee00ff"
A_ASSET_LIGHTER_BG="ee00ff"
A_ASSET_VARIOUS_DARK1="ee00ff"
A_ASSET_VARIOUS_DARK2="ee00ff"
A_ASSET_VARIOUS_DARK3="ee00ff"
A_GNOME_PANEL_BG="ee00ff"
A_GNOME_PANEL_BORDER="ee00ff"
A_GTK2_TOOLBAR="ee00ff"
A_GTK2_TOOLBAR_DARK="ee00ff"
A_CLOSE_BUTTON_GREY="ee00ff"
A_LIGHT_BG="ee00ff"
A_SWITCH_OFF_BG="ee00ff"
A_LIGHT_FG="ee00ff"
## GTK2
A_GTK2_SENSITIVE_STROKE="ee00ff"
A_GTK2_INSENSITIVE_FG_COLOR="ee00ff"
A_GTK2_INSENSITIVE_STROKE="ee00ff"
A_GTK2_BUTTON_HOVER="ee00ff"
A_GTK2_SCROLLBAR_BG="ee00ff"
A_GTK2_SCROLLBAR_FG="ee00ff"
A_GTK2_SCROLLBAR_FG_HOVER="ee00ff"
A_GTK2_SLIDER_STROKE="ee00ff"
A_GTK2_LIGHT_SENSITIVE_BG="ee00ff"
A_GTK2_LIGHT_SENSITIVE_STROKE="ee00ff"
A_GTK2_LIGHT_INSENSITIVE_BG="ee00ff"
A_GTK2_LIGHT_INSENSITIVE_FG="ee00ff"
A_GTK2_LIGHT_INSENSITIVE_STROKE="ee00ff"
A_GTK2_LIGHT_ACTIVE_BG="ee00ff"
A_GTK2_LIGHT_ACTIVE_STROKE="ee00ff"
A_GTK2_LIGHT_SCROLLBAR_BG="ee00ff"
A_GTK2_LIGHT_SCROLLBAR_FG="ee00ff"
A_GTK2_LIGHT_SCROLLBAR_FG_HOVER="ee00ff"
A_GTK2_LIGHT_SCROLLBAR_BORDER="ee00ff"
A_GTK2_LIGHT_SLIDER_STROKE="ee00ff"
A_GTK2_LIGHT_TAB_BORDER="ee00ff"
A_GTK2_LIGHT_MENUBAR_STROKE="ee00ff"
A_GTK2_LIGHT_FRAME_BORDER="ee00ff"
## Openbox
A_OPENBOX_MENU_ITEM_BG="ee00ff"
A_OPENBOX_MENU_ITEM_FG="ee00ff"
A_OPENBOX_MENU_TITLE_BG="ee00ff"
## Plank
A_PLANK_FILL_START="53;;57;;69;;242"
A_PLANK_FILL_END="53;;57;;69;;242"
A_PLANK_OUTER_STROKE="22;;26;;38;;255"
A_PLANK_INNER_STROKE="53;;57;;69;;0"

# Solarized colors
## Common
S_YELLOW="ee00ff"
S_ORANGE="ee00ff"
S_RED="ee00ff"
S_MAGENTA="ee00ff"
S_VIOLET="ee00ff"
S_BLUE="ee00ff"
S_CYAN="ee00ff"
S_GREEN="ee00ff"
## Dark
S_BASE03="ee00ff"
S_BASE02="ee00ff"
S_BASE01="ee00ff"
S_BASE00="ee00ff"
S_BASE0="ee00ff"
S_BASE1="ee00ff"
S_BASE2="ee00ff"
S_BASE3="ee00ff"

declare -A REPLACE
REPLACE[$A_BASE]=$S_BASE03
REPLACE[$A_TEXT]=$S_BASE0
REPLACE[$A_BG]=$S_BASE02
REPLACE[$A_FG]=$S_BASE0
REPLACE[$A_SELECTED_FG]=$S_BASE3
REPLACE[$A_SELECTED_BG]=$S_BLUE
REPLACE[$A_WARNING]=$S_ORANGE
REPLACE[$A_ERROR]=$S_RED
REPLACE[$A_SUCCESS]=$S_GREEN
REPLACE[$A_DESTRUCTIVE]=$S_RED
REPLACE[$A_SUGGESTED]=$S_CYAN
REPLACE[$A_DROP_TARGET]=$S_YELLOW
REPLACE[$A_WM_BUTTON_CLOSE_BG]=$S_RED
REPLACE[$A_WM_BUTTON_CLOSE_HOVER_BG]=$S_ORANGE
REPLACE[$A_WM_BUTTON_CLOSE_ACTIVE_BG]=$S_RED
REPLACE[$A_WM_ICON_CLOSE_BG]=$S_BASE03
REPLACE[$A_WM_BUTTON_HOVER_BG]=$S_BASE00
REPLACE[$A_WM_BUTTON_ACTIVE_BG]=$S_BLUE
REPLACE[$A_WM_BUTTON_HOVER_BORDER]=$S_BASE03
REPLACE[$A_WM_ICON_BG]=$S_BASE1
REPLACE[$A_WM_ICON_UNFOCUSED_BG]=$S_BASE00
REPLACE[$A_WM_ICON_HOVER_BG]=$S_BASE1
REPLACE[$A_WM_ICON_ACTIVE_BG]=$S_BASE3
REPLACE[$A_WINDOW_BG]=$S_BASE02
REPLACE[$A_DARK_SIDEBAR_FG]=$S_BASE00
REPLACE[$A_WHITE]=$S_BASE3
REPLACE[$A_LIGHT_MENUBAR]=$S_BASE3
REPLACE[$A_DARKEST2]=$S_BASE03
REPLACE[$A_DARK_BUTTON]=$S_BASE03
REPLACE[$A_LIGHT_BUTTON]=$S_BASE02
REPLACE[$A_MODAL]=$S_BASE03
REPLACE[$A_ASSET_DARK]=$S_BASE03
REPLACE[$A_ASSET_DARK2]=$S_BASE02
REPLACE[$A_ASSET_GREY]=$S_BASE00
REPLACE[$A_ASSET_BORDER]=$S_BASE00
REPLACE[$A_ASSET_VARIOUS_DARK1]=$S_BASE00
REPLACE[$A_ASSET_VARIOUS_DARK2]=$S_BASE03
REPLACE[$A_ASSET_VARIOUS_DARK3]=$S_BASE03
REPLACE[$A_GNOME_PANEL_BG]=$S_BASE03
REPLACE[$A_GNOME_PANEL_BORDER]=$S_BASE03
REPLACE[$A_GTK2_TOOLBAR]=$S_BASE0
REPLACE[$A_GTK2_TOOLBAR_DARK]=$S_BASE00
REPLACE[$A_CLOSE_BUTTON_GREY]=$S_BASE02
REPLACE[$A_LIGHT_BG]=$S_BASE2
REPLACE[$A_GTK2_INSENSITIVE_FG_COLOR]=$S_BASE01
REPLACE[$A_SWITCH_OFF_BG]=$S_BASE01
REPLACE[$A_LIGHT_FG]=$S_BASE00
# Openbox
REPLACE[$A_OPENBOX_MENU_ITEM_BG]=$S_BASE03
REPLACE[$A_OPENBOX_MENU_ITEM_FG]=$S_BASE0
REPLACE[$A_OPENBOX_MENU_TITLE_BG]=$S_BASE02
# GTK2 tweaks
REPLACE[$A_ASSET_LIGHTER_BG]="ee00ff"
REPLACE[$A_OTHER_LIGHT_BUTTON]="ee00ff"
REPLACE[$A_GTK2_SENSITIVE_STROKE]="ee00ff"
REPLACE[$A_GTK2_INSENSITIVE_STROKE]="ee00ff"
REPLACE[$A_GTK2_BUTTON_HOVER]="ee00ff"
REPLACE[$A_GTK2_SCROLLBAR_BG]="ee00ff"
REPLACE[$A_GTK2_SCROLLBAR_FG]="ee00ff"
REPLACE[$A_GTK2_SCROLLBAR_FG_HOVER]="ee00ff"
REPLACE[$A_GTK2_SLIDER_STROKE]="ee00ff"
REPLACE[$A_GTK2_LIGHT_SENSITIVE_BG]="ee00ff"
REPLACE[$A_GTK2_LIGHT_SENSITIVE_STROKE]="ee00ff"
REPLACE[$A_GTK2_LIGHT_INSENSITIVE_BG]="ee00ff"
REPLACE[$A_GTK2_LIGHT_INSENSITIVE_FG]="ee00ff"
REPLACE[$A_GTK2_LIGHT_INSENSITIVE_STROKE]="ee00ff"
REPLACE[$A_GTK2_LIGHT_ACTIVE_BG]="ee00ff"
REPLACE[$A_GTK2_LIGHT_ACTIVE_STROKE]=$S_BLUE
REPLACE[$A_GTK2_LIGHT_SCROLLBAR_BG]="ee00ff"
REPLACE[$A_GTK2_LIGHT_SCROLLBAR_FG]="ee00ff"
REPLACE[$A_GTK2_LIGHT_SCROLLBAR_FG_HOVER]="ee00ff"
REPLACE[$A_GTK2_LIGHT_SCROLLBAR_BORDER]="ee00ff"
REPLACE[$A_GTK2_LIGHT_SLIDER_STROKE]="ee00ff"
REPLACE[$A_GTK2_LIGHT_TAB_BORDER]="ee00ff"
REPLACE[$A_GTK2_LIGHT_MENUBAR_STROKE]="ee00ff"
REPLACE[$A_GTK2_LIGHT_FRAME_BORDER]="ee00ff"
# Plank tweaks
REPLACE[$A_PLANK_FILL_START]="7;;54;;66;;255"
REPLACE[$A_PLANK_FILL_END]="7;;54;;66;;255"
REPLACE[$A_PLANK_OUTER_STROKE]="5;;18;;29;;255"
REPLACE[$A_PLANK_INNER_STROKE]="0;;43;;54;;0"

# Pull the Arc source
echo "### Downloading Arc source"
wget --quiet "https://github.com/jnsh/arc-theme/releases/download/${ARCVERSION}/arc-theme-${ARCVERSION}.tar.xz"
tar -xJf "arc-theme-${ARCVERSION}.tar.xz"
rm "arc-theme-${ARCVERSION}.tar.xz"

CWD="`pwd`/arc-theme-${ARCVERSION}"
cd "${CWD}"

echo "### Applying patch(es)"

echo "### Optimising SVGs"
find . -name "*.svg" -exec inkscape {} --vacuum-defs --export-plain-svg={} \;

FILETYPES=('.scss' '.svg' '.xpm' '.xml' 'rc' '.theme')

echo "### Replacing arc colors with solarized colors"
for filetype in "${FILETYPES[@]}"
do
    echo "## Replacing in ${filetype}"
    for K in ${!REPLACE[@]}
    do
        find . -type f -name "*${filetype}" -exec sed -i "s/${K}/${REPLACE[$K]}/Ig" {} \;
    done
done

# Correct index.theme metadata & output directories
for PATTERN in "index.theme*" "metacity-theme-*.xml"; do
    find "${CWD}/common" -name "${PATTERN}" -exec sed -i "s/Arc/SolArc/g" {} \;
done
sed -i "s/Arc/SolArc/g" configure.ac;
for FILE in meson.build meson_options.txt; do
    sed -i "s/Arc/SolArc/g" $FILE;
    sed -i "s/arc-theme/solarc-theme/g" $FILE;
done

echo "### Patching complete! You may now run autogen.sh & make in arc-theme-${ARCVERSION} as you wish"

